### ISSUE TITLE
php artisan langman:trans addslashes error

### ISSUE THREAD

**Issue by dragonfire1119** [themsaid/laravel-langman#15]
How to create the issue:

```
php artisan langman:trans nav.new_item
> Create new item
```

Error:
```
addslashes() expects parameter 1 to be string, array given
```

Laravel Version: 5.2

**Comment by themsaid** [comment]
Was that using a vendor translation file?

**Comment by dragonfire1119** [comment]
@themsaid No I removed the vendor directory.

**Comment by themsaid** [comment]
Working on this and will update you once it's fixed.

Thanks for reporting :)

**Comment by themsaid** [comment]
This error is now fixed since https://github.com/themsaid/laravel-langman/releases/tag/v1.2.0
