### ISSUE TITLE
php artisan langman:trans vendor error

### ISSUE THREAD

**Issue by dragonfire1119** [themsaid/laravel-langman#16]
How to create the issue:

1. Create a vendor directory in lang

```
php artisan langman:trans nav.new_item
> Create item
```

Error: 
```
Undefined index: vendor
```

Laravel Version: 5.2

**Comment by themsaid** [comment]
Vendor translations are not supported yet, i'm working on that at the moment.

**Comment by dragonfire1119** [comment]
@themsaid If there not support couldn't you temporary not show the error? Because just having a vendor directory throws the error.

**Comment by vpratfr** [comment]
Duplicate with #3

**Comment by themsaid** [comment]
This is also fixed in https://github.com/themsaid/laravel-langman/releases/tag/v1.2.0
