### ISSUE TITLE
Bugs in windows environment

### ISSUE THREAD

**Issue by rsdev000** [themsaid/laravel-langman#17]
Hi

Don't know if it happens on other platforms but it happens on windows.
Verified on a fresh laravel install.

![show01](https://cloud.githubusercontent.com/assets/9252353/14381721/66647370-fd80-11e5-9d65-7846033457b8.png)

So far, so good.

The issue comes up when I try to add a new translation

![error01](https://cloud.githubusercontent.com/assets/9252353/14381749/97649216-fd80-11e5-9949-f48f5371f97a.png)

The problem is in ```Manager.php``` - ```fillKeys($fileName, array $keys)```method.

```$filePath = $this->path."/{$languageKey}/{$fileName}.php";``` : first translation results in ```C:\Work\www\projects\dummy\resources\lang/C:\Work\www\projects\dummy\resources\lang\en/auth.php```

The workaround was ```$filePath = "{$languageKey}/{$fileName}.php";``` . The result is ```C:\Work\www\projects\dummy\resources\lang\en/auth.php``` and new translations were added with success.

![success](https://cloud.githubusercontent.com/assets/9252353/14381932/e0a41db0-fd81-11e5-8d51-bcb5fc1907f2.png)

The sync command has issues too:

![error02](https://cloud.githubusercontent.com/assets/9252353/14382423/8a0b3d86-fd85-11e5-99bb-7de4920b8628.png)

Then added another translation mannualy and tried the missing command

![error03](https://cloud.githubusercontent.com/assets/9252353/14382490/28d5d7b4-fd86-11e5-958b-783799157827.png)

There's a success message but the translation was not added to ```es/auth.php```

The remove command fails too.

![error04](https://cloud.githubusercontent.com/assets/9252353/14382592/ccfbc8d0-fd86-11e5-96ed-893abe46b853.png)

Cheers

**Comment by rsdev000** [comment]
Hi 

Tested with you latest changes on master and the issues are gone :)

**Comment by themsaid** [comment]
OH .. THANK YOU for following up :)
Please let me know if I can make the package better.

**Comment by themsaid** [comment]
This is now fixed in v1.2.0 https://github.com/themsaid/laravel-langman/releases/tag/v1.2.0
