### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by rsdev000** [themsaid/laravel-langman#19]
Hi. It's just an idea but I think it could be useful.

-i think the ```show command``` can be improved.

One improvement consists in adding an optional param ```language```.

```php artisan langman:show auth en``` / ```php artisan langman:show auth.failed en``` to show the auth translations for one language. If the language passed does not exists, the show the languages available (maybe another command to show the available languages? )

Another improvement is about how the translations are displayed when you have several languages and/or long strings.
Transposing the data? Display two languages at a time and repeat the header? Setting based ?

With five languages which is not so uncommon in european apps (en, fr, de, es, pt) it becomes a mess on the screen.

![messy](https://cloud.githubusercontent.com/assets/9252353/14403214/eac941a6-fe46-11e5-8f3a-39b6f3ba99c3.png)

Keep up the good work.

**Comment by themsaid** [comment]
Thank you for this valuable feedback 👍 
I'll be looking into that and hopefully come up with suitable solutions.

**Comment by rsdev000** [comment]
You're welcome. I think the ability to show the translations for one language is the most useful improvement.

**Comment by themsaid** [comment]
@rsdev000 now you can display only the specified languages via the `--lang` option, is that enough for you? If the languages are too much you may display only the ones you need.
