### ISSUE TITLE
Lower PHP requirement

### ISSUE THREAD

**Issue by vpratfr** [themsaid/laravel-langman#2]
You currently require PHP7, which is way above the requirement set by Laravel itself. Could you update the composer file so that we can still install it?

**Comment by themsaid** [comment]
I do understand that it makes more sense to support PHP >=5.5.9 just like laravel, however building packages is some type of practise for me where I'm free to pick the tools I need to learn more about, and that was why I built it using PHP7, although I didn't use much of the power of PHP7 in the code base but I learnt a lot getting to know the possibilities.

I can support PHP5.* in a upcoming minor release in the next couple of days if that request was sent again, meanwhile may I ask you why haven't u upgrade to PHP7 yet? I just need to understand if you don't mind :)

**Comment by vpratfr** [comment]
Reasons are multiple : 

- on Debian not long back the stable version for production servers was still PHP 5.5 (with apt-get by default), so a lot of servers are running that version
- some of my clients are running PHP 5.5 and I cannot force them to switch to PHP 7
- minimal PHP version used by Laravel is 5.5 and thus I would expect any package based on L5 to follow minimal requirements for that version of Laravel (if you support Laravel 4 then would make sense to have your PHP version to match the one of Laravel 4.x).

Please note that I am running PHP 7 inside my homestead VM, however, I do not want to require that version in my composer file (for all reasons above).

Your package looks great, I don't need a GUI and mostly need a tool to keep my translation files in sync between languages so that I can send them directly to people translating it. So that does what I need but can't install it yet :) Looks promising though.

**Comment by themsaid** [comment]
Alright, will make a release in the next couple of days with PHP<7 support.

**Comment by dikiaap** [comment]
Sounds good, waiting for PHP >= 5.5.9 support.

**Comment by eskrano** [comment]
Wait php >= 5.5 support

**Comment by themsaid** [comment]
The package now supports PHP >= 5.5.9 since `v1.1.0` https://github.com/themsaid/laravel-langman/releases/tag/v1.1.0
