### ISSUE TITLE
Sync is ignoring anything outside views

### ISSUE THREAD

**Issue by vpratfr** [themsaid/laravel-langman#21]
There are lots of places where we have messages: controllers, validation, events, etc. All of them are not taken into account, just the views.

This would be fair to incorporate those classes into the sync process.

**Comment by ahmedash95** [comment]
@themsaid i think you should close this issue now :D.

**Comment by vpratfr** [comment]
@ahmedash95 Question : 

I have translations for enums. Here is some code : 

### Enum declaration in `config/enums.php`

```
return [ 'gender' => [ 'MALE', 'FEMALE', ] ];
```

### Translations in `resources/lang/en/enums.php`

```
return [ 'gender' => [ 
    'MALE' => 'Man', 
    'FEMALE' => 'Woman',
] ];
```

### Views can use it from a model for example:

```
{{ trans('enums.gender.' . $person->gender); }}
```

What happens in that case when you sync translations? What is the content of `enums.php` after the sync process?

**Comment by ahmedash95** [comment]
@vpratfr config/enums.php out of sync scope becase it just an array doesn't use any lang methods! . or I misunderstand ?

**Comment by themsaid** [comment]
```
{{ trans('enums.gender.' . $person->gender); }}
```

The above method call will be ignored by the sync command as it contains a dynamic key, only specific key calls are considered. If you have an idea on how to support this type of calls I'll be glad to consider it.

**Comment by vpratfr** [comment]
There is no real way to support it. However, good to know it is ignored, I think that is the best way to handle it. 

How about the existing translation messages in `resources/lang/en/enums.php`? Will they get erased?

It would be handy (and maybe safe) to be able to specify a list of files to ignore in the lang folders when sync-ing.

**Comment by vpratfr** [comment]
Actually I think we are mixing two different things: 

- Process of finding/removing translations from the code (views, classes) and updating the translation files with that (potentially only touching the default language files, not translations).
- Process of simply synchronizing translation files accross languages (I have a set of files for default language `en` (could be another default lang) which is supposed to be complete, and now I want to add/remove missing keys from other language files)

Both of them are doing something different. And I don't really know what your package does. Maybe it would be a good idea to have a command for each?

**Comment by themsaid** [comment]
Nope, it won't get erased, it'll stay untouched.

Regarding ignoring files, why would you want to ignore a file? I don't mind having an option `--ignore=enums,users,auth` but curious about the use cases.

Regarding your other opened issue, is it still not working? Did you succeed figuring out what was wrong?

**Comment by vpratfr** [comment]
Ignoring a file is in case a translation is not in code anymore and you remove them from language files.

If you don't do any removal of unused translation keys, then ignoring is not really necessary.

**Comment by themsaid** [comment]
I'm not sure I quite understand the use case, do you mean if you remove the `trans()` calls for specific keys from code and you want to keep the language file although it's useless?

**Comment by themsaid** [comment]
v1.2.2 now looks inside the app directory in addition to the views directory.
