### ISSUE TITLE
all tests is broken

### ISSUE THREAD

**Issue by ahmedash95** [themsaid/laravel-langman#25]
i'm trying to solve the problem but i think you could do it faster than me , could you please check all tests 

@themsaid

**Comment by themsaid** [comment]
All tests where?

**Comment by themsaid** [comment]
If you mean the PR then let's discuss it there.

**Comment by ahmedash95** [comment]
@themsaid i didn't mean the PR . could you please try to run test with a fresh install of laravel with langman ?

**Comment by themsaid** [comment]
How do you run tests after pulling langman into laravel?

**Comment by ahmedash95** [comment]
``` cd vendor/themsaid/laravel-langman ``` then ``` composer install ``` then ``` phpunit ```

**Comment by themsaid** [comment]
Can you share the errors coming from running the tests?

**Comment by ahmedash95** [comment]
http://i.imgur.com/mAEMvdS.png

**Comment by themsaid** [comment]
I think the script isn't able to create the temporary test files, anyway it's recommended that you develop the package outside laravel.

**Comment by ahmedash95** [comment]
how can i test my modifications if i developing the package outside laravel ?

**Comment by themsaid** [comment]
That's the point of testing :) Your tests need to be isolated. Anyway you should track teh reason behind the failing tests on your system, it's not a general issue as the tests pass on Travis: https://travis-ci.org/themsaid/laravel-langman

**Comment by ahmedash95** [comment]
really weird , i will try to fix this issue :D , thanks for your time
