### ISSUE TITLE
New keys created by langman should be in default language rather than empty

### ISSUE THREAD

**Issue by vpratfr** [themsaid/laravel-langman#27]
Langman creates new files with new keys which are empty.

Problem is that translators who receive those files will have to look into the original language files to know what the original message is before they can translate it.

It would be useful to have a default language instead of an empty string.

**Comment by themsaid** [comment]
The point of empty strings is for easily finding them with the `langman:missing` command, if we fill the new keys we won't be able to identify keys that need translation.

**Comment by themsaid** [comment]
A import/export feature is planned here, I think it'll work for the case you're mentioning: https://github.com/themsaid/laravel-langman/issues/31

**Comment by vpratfr** [comment]
Yes, that would work too.
