### ISSUE TITLE
Sub-directories translations

### ISSUE THREAD

**Issue by vpratfr** [themsaid/laravel-langman#3]
3rd party packages sometimes allow to publish translation files.

Those file are usually located inside a subfolder of lang. For instance:

```
lang
  |_ en
  |_ fr
  |_ es
  |_ vendor
    |_ package1
    | |_ en
    | |_ fr
    | |_ es
    |_ package2
      |_ en
      |_ es
```

- Is that supported by your tool? 
- Will package1/package2 get updated too?
- Will `fr` be created in package2 folder?

**Comment by themsaid** [comment]
That's not supported at the moment, also nested keys:

```
'names' =>['first' => 'first name', 'last' => 'last name']
```

Both are not supported yet. I'm planning to work on that sometime soon, I'll appreciate contributions though.

**Comment by vpratfr** [comment]
Oh. Ok. I guess the vendor package issue could be worked around by allowing multiple paths in your config file and ditching all folders with name having more than 2 characters.

Nested keys is a rather big problem too, that's very common to have nested keys in translation files (that includes the default files provided by Laravel)

**Comment by themsaid** [comment]
yes, these two cases need to be covered, I'll put some time for them during this week :) Hopefully can come up with something soon.

**Comment by themsaid** [comment]
The package now supports dealing with vendor translation files since v1.2.0 https://github.com/themsaid/laravel-langman/releases/tag/v1.2.0
