### ISSUE TITLE
Support for nested keys

### ISSUE THREAD

**Issue by vpratfr** [themsaid/laravel-langman#4]
opening another issue to request support for nested keys (as mentioned in #3, but to keep feature requests separated).

**Comment by themsaid** [comment]
- [x] `langman:show`
- [x] `langman:find`
- [ ] `langman:missing`
- [ ] `langman:Sync`
- [ ] `langman:remove`
- [ ] `langman:trans`

**Comment by themsaid** [comment]
The package now supports dealing with nested keys since v1.2.0 https://github.com/themsaid/laravel-langman/releases/tag/v1.2.0
