### ISSUE TITLE
Controllers support?

### ISSUE THREAD

**Issue by benjamincrozat** [themsaid/laravel-langman#40]
Could it be possible? It would be very useful for flash messages.

**Comment by themsaid** [comment]
Helo @benjamincrozat, the package scans al views and all files in your app directory. So I believe controllers are scanned too, no?

**Comment by benjamincrozat** [comment]
Yes, I didn't saw it because I forgot to prefix keys in the trans() function. Sorry!

**Comment by themsaid** [comment]
No worries :)
