### ISSUE TITLE
Show translation in default language

### ISSUE THREAD

**Issue by markvaneijk** [themsaid/laravel-langman#42]
I have a very large translation database and translating it now is quite difficult even with this awesome package. It would be nice if the text that I need to translate is shown in the already available translation, for example the default language of the app (app.locale config).

So if I have my app with default language in English, than I would like to translate it to some other language. But I need to see what the actual text is I need to translate in the default app language, because the key is not self explanatory enough.

It would be really nice if this would be an option.

**Comment by themsaid** [comment]
This is now done by @fergthh and will be released with the next version.

Thank you for the suggestion :)

**Comment by markvaneijk** [comment]
Great! 👍🏻
