### ISSUE TITLE
Get ready for Laravel 5.3

### ISSUE THREAD

**Issue by rsdev000** [themsaid/laravel-langman#46]
Hello

Can you update composer.json to allow 5.3 illuminate components please ?

Cheers

**Comment by themsaid** [comment]
I think I'll do that after the release, need to make sure everything works on 5.3 when it's final :)

**Comment by rsdev000** [comment]
I undestand. Forked the package and didn't find any problem under laravel 5.3-dev. 
Cheers

**Comment by themsaid** [comment]
👍 great.

Will make more checks once 5.3 is announced too, to make sure everything is wokring as expected :)
