### ISSUE TITLE
How we can use it in a project multilang Ar En?

### ISSUE THREAD

**Issue by lb308** [themsaid/laravel-langman#65]
Hi all thanks a lot, I am new to laravel I want to make site with two languages Arabic and English, how can I switch between using this package, thanks

**Comment by nicolasbeauvais** [comment]
This package will help you manage translations, not switch between languages in your UI.

You should read https://laravel.com/docs/5.5/localization
or this easy to follow tutorial: https://laracasts.com/discuss/channels/tips/example-on-how-to-use-multiple-locales-in-your-laravel-5-website
