### ISSUE TITLE
Disable URL on  production

### ISSUE THREAD

**Issue by robsontenorio** [themsaid/laravel-langman#68]
Is that possible disable mysite.com/langman url on production environment?

I think its a security issue.

**Comment by hasandz** [comment]
You can disable service provider for production in AppServiceProvider.php

```php
if (!$this->app->environment('production'))
{
    $this->app->register(\Themsaid\LangmanGUI\LangmanServiceProvider::class);
}
```

**Comment by nicolasbeauvais** [comment]
This package doesn't define any routes, you are probably talking about https://github.com/themsaid/laravel-langman-gui

You can override the `registerRoutes` method of the `LangmanServiceProvider` by defining your own service provider for the package https://github.com/themsaid/laravel-langman-gui/blob/master/src/LangmanServiceProvider.php#L49
