### ISSUE TITLE
Please fix with php 7.4

### ISSUE THREAD

**Issue by Nelie-Taylor** [themsaid/laravel-langman#96]
- Laravel Version: 6.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:

![image](https://user-images.githubusercontent.com/12018657/66333805-ee435380-e961-11e9-986e-dc80957df147.png)

### Steps to reproduce:
Thank you so much.

**Comment by gerpo** [comment]
Maybe you could submit a pull request? 7.4 is not yet officially released, but if you need it now you could help the community by helping to make the code ready for the release. That's the beauty of open source.

**Comment by lauhakari** [comment]
Fixed in #93 :)

**Comment by adelynx** [comment]
@Nelie-Taylor, this is the fix I have done and worked for me. I am using the package from my private repo as this one is not maintained anymore. I do suggest you to fork the repo to your account and use it from there after adding the fix. Good luck 

```php
foreach ($allLanguages as $languageKey) {
       $original[$languageKey] =
               isset($values[$languageKey])
                      ? $values[$languageKey]
                      : (isset($filesContent[$fileName][$languageKey][$key]) ? $filesContent[$fileName][$languageKey][$key] : '');
      }
```

**Comment by Lemmynjash** [comment]
@adelynx worked for me thanks alot

**Comment by abdialeh** [comment]
@adelynx worked for me too, thanks
